apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: taskflow-backend-external-secret
  namespace: taskflow
  labels:
    app.kubernetes.io/name: taskflow-backend
    app.kubernetes.io/component: external-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: taskflow-ssm-store
    kind: ClusterSecretStore
  target:
    name: taskflow-backend-secret
    creationPolicy: Owner
  data:
  - secretKey: db_username
    remoteRef:
      key: /taskflow/db_username
  - secretKey: db_password
    remoteRef:
      key: /taskflow/db_password
  - secretKey: jwt_secret
    remoteRef:
      key: /taskflow/jwt_secret
  - secretKey: db_host
    remoteRef:
      key: /taskflow/db_host
  - secretKey: db_name
    remoteRef:
      key: /taskflow/db_name