apiVersion: v1
kind: ServiceAccount
metadata:
  name: taskflow-backend-sa
  namespace: taskflow
  labels:
    app.kubernetes.io/name: taskflow-backend
    app.kubernetes.io/component: backend
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::569360421892:role/taskflow-pod-role