apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- backend/serviceaccount.yaml
- backend/deployment.yaml
- backend/service.yaml
- backend/hpa.yaml
- backend/pdb.yaml
- backend/cluster-secret-store.yaml
- backend/external-secret.yaml
- frontend/deployment.yaml
- frontend/service.yaml
- frontend/hpa.yaml
- frontend/pdb.yaml
- ingress/ingress.yaml
- network-policy/network-policy.yaml